# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-05 21:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0003_auto_20181112_1629'),
        ('gameplay', '0004_auto_20170904_0947'),
    ]

    operations = [
    ]
